### ISSUE TITLE
doesn't ignore arguments after --

### ISSUE THREAD

**Issue by rosenfeld** [jimweirich/rake#115]
``` shell
rake some_task -- some_arg
```

Raises an error after running some_task:

```
Don't know how to build task some_arg.
```

**Comment by drbrain** [comment]
Rake processes arguments first, obeying `--`.

Then rake discovers task names and env-style rake arguments.

If you use `some_arg=` it will be treated as an argument.

Otherwise task names after `--` will be treated as task names.

@jimweirich will have to decide if he wants to change the behavior of rake, but it will be difficult to implement since rake does not know where `--` appeared.

**Comment by rosenfeld** [comment]
I'm not sure if it doesn't know. If you try to use some option after `--`, like `--anything=any`, rake won't complain, but if you try to include some unsupported option before the `--` it will complain about an unsupported option.

**Comment by drbrain** [comment]
```
$ ruby -roptparse -e 'p ARGV; OptionParser.new.parse! ARGV; p ARGV' -- foo -- bar
["foo", "--", "bar"]
["foo", "bar"]
```

**Comment by rosenfeld** [comment]
So it would be just a matter of popping out all extra arguments from ARGV after '--'  to a separate array before passing it to OptionParser, right?

**Comment by jimweirich** [comment]
There is no expectation for rake to ignore arguments after a "--".

In fact, there is currently a proposal to use "--" as an argument/option separator.

In light of that, I'm not changing the behavior of rake w.r.t. -- for the time being.
