### ISSUE TITLE
Can any one help me ,what's wrong in this code.....

### ISSUE THREAD

**Issue by Mallikarjunay** [jimweirich/rake#153]
$msg_welcome = "Welcome to rake tutorials"

task :default do
              display "msg"
end

def display(message)
          mess = $message+"_welcome"
          puts "#{mess}"
end

Here the print is not proper...

**Comment by damphyr** [comment]
There's so many things wrong with your code that I'm having trouble understanding what it is you're actually trying to do. Here's the two most important:

You're assigning a global variable ($msg_welcome) which you never use. 
You're referencing a global variable ($message) which is never assigned a value in place of the parameter you're passing to the method.

So I'm not surprised that it does not print what you expect.

**Comment by thentenaar** [comment]
From what I gather from your code, you intend to have the `:default` task display the message in the global variable `$msg_welcome`. I also noticed you were trying to reference `$msg_welcome` by concatenating `message` (the parameter to `display`) with '_welcome'. In order to do that, you'd have to do:

``` ruby
mess = eval "$#{message}_welcome"
```

since `$message` is interpreted to mean _the global variable, message_, and in fact, if I modify that one line, your code seems to work in the expected way.

Here's a different, and perhaps slightly clearer, way to do the same:

``` ruby
$msg = {
  :welcome => 'Welcome to rake tutorials'
}

task :default do
  display :welcome
end

def display(message)
  puts $msg[message]
end
```

Hope that helps!

**Comment by jimweirich** [comment]
Not a Rake issue.  Closing.
