### ISSUE TITLE
--verbose option does not work

### ISSUE THREAD

**Issue by sonots** [jimweirich/rake#164]
although -v option works by some reasons. 

Also, this test looks wierd https://github.com/jimweirich/rake/blob/master/test/test_rake_application_options.rb#L356,

```
- flags('--verbose', '-V') do |opts|
+ flags('--verbose', '-v') do |opts|
```

should it be like above?

**Comment by jimweirich** [comment]
The verbose option is a little weird.  At one point in time, the default for Rake was to not print out the system commands that were executed. The verbose flag would turn that out so you could see what was executing.  At some point we changed the default so that it is verbose by default. At that point the verbose flag became redundant. 

The --quiet/--silent flags are used to do the opposite of --verbose, and I validated that both of these seem to be doing the right thing.

And yes, that test is wonky (but fixed now).

Thanks.
