### ISSUE TITLE
Multitask, task and shared prereqs

### ISSUE THREAD

**Issue by dekz** [jimweirich/rake#169]
What is the expected behaviour regarding MultiTask and shared prereqs it may have. Say I want to run task `:a:` and task `:b` concurrently but they both have a prerequisite of task `:c`. 

How many times should `:c` be executed?

What if `:c` is a main task in the multitask, how many times should it be executed?

``` ruby
require 'rake'

task :c  do
  puts "c"
end

task :a => [:c] do
  puts "a"
end

task :b => [:c] do
  puts "b"
end

multitask :run_1 => [:a, :b]
multitask :run_2 => [:c, :a, :b]

```

I expected the `run_2` to have the same behaviour as `run_1` in that, `:c` is only called once. I.e I would have expected `Task#already_invoked` to be true and for it to not execute again. 

If this is incorrect behaviour, I believe it may have to do with the Promise from multitask and the normal Task interaction. Inside [Promise#initialize](https://github.com/jimweirich/rake/blob/master/lib/rake/promise.rb#L20), arguments are duped which means two Task `:a`'s are created and the `@already_invoked` condition can be met on both.

**Comment by jimweirich** [comment]
I agree, that's a bug.  I'll investigate when I get a chance.

**Comment by jimweirich** [comment]
Good catch.

It seems the futures objects created by the thread pool automatically duplicate any incoming arguments. This is supposedly done for thread safety.  Unfortunately duplicating tasks will also duplicate their "already_run" flag, so the "C" task is running once for the original and once for the duplicate.

Since we only invoke the task within future and invoking is already thread-safe, there is no need for the future to auto-dup its arguments.  I've removed the auto-dup feature and that seems to fix the problem.

The fix is pushed to master and will be in the next Rake release.

Thanks for the bug report.

**Comment by dekz** [comment]
Thanks Jim
