### ISSUE TITLE
Expose API for manipulating pre-existing tasks.

### ISSUE THREAD

**Issue by dchelimsky** [jimweirich/rake#17]
Some libs ship with pre-defined rake tasks. Some users of these libs want to amend their configurations by adding and/or overriding options. The only way I know how to do this is to remove the pre-defined task and redefine your own, but there is no simple API (that I am aware of) to do this, so people end up writing variations of this:

<pre>
Rake::TaskManager.class_eval do
  def remove(task_name)
    @tasks.delete(task_name.to_s)
  end
end
</pre>

I think it would be very helpful for Rake to expose an API for manipulating pre-defined tasks in a few different ways:

`Rake.remove(:foo)` would remove a task.

`Rake.replace(:foo) {|t| ... }` would remove a task and then yield a newly created task of the same type.

`Rake.amend(:foo) {|t| ...}` would find the task and yield it.

These three methods (or similar) would provide a world of flexibility to library authors and consumers alike.

**Comment by leehambley** [comment]
Plus one, the fact that Rake's default behavior is to extend a task definition is always a jarring surprise to people, and is rarely useful (at least in my experience) - Ruby has a way for extending functionality (ala Thor tasks, reopening methods, and `super`) -- _Please_ for the love of sanity implement this Jim.

**Comment by dchelimsky** [comment]
Jim - if you're open to the idea, I'll be glad to take a crack at it.

@leehambley, I think changing the default behavior would be a big change for a lot of unsuspecting people, even if documented. Though, deprecating it w/ a formal deprecation message when the same name is declared twice, and then pointing the user to the new API method (amend, in the original post in this thread, but whatever) would be OK if Jim's OK w/ it.

**Comment by justinko** [comment]
+1

**Comment by jimweirich** [comment]
I have hesitated to build too much task manipulation because I worry about composibility of Rakefiles.  It strikes me that allowing one Rakefile to do surgery on tasks defined in another Rakefile is akin to pathological coupling.  If two rakefiles attempt to manipulate the tasks in third rakefile, how do they avoid stepping on each others toes.

That being said, there are fairly standard ways for doing most of what you asked for above.  For example, the replace command is simply:

```
task(:foo).clear
task :foo => [new_deps] do ... end
```

And amend is simply:

```
task(:foo).tap { |t| ... }
```

(There is no standard for remove at the moment).

Here's the composibility problem:

(1) Project A defines task foo
(2) Plugin B clears foo and substitutes its own functionality.
(3) Plugin C also substitutes its own functionality for foo, wiping out the functionality required by B.

If task surgery is encouraged, I fear we could get into a situation where plugins regularly break each other's tasks.  Hence my conservative approach.

What would really thrill me is if someone could come up with a AOP style of task modification that would clearly allow multiple plugins to enhance each others tasks without stepping on each others toes.

**Comment by dchelimsky** [comment]
@jimweirich - everything you say makes perfect sense. I wasn't aware of `task(:foo).clear`, and that is a perfectly acceptable solution for my use case. `remove` was suggested only as a means to replace.

FYI - I don't see this documented in the rdoc at http://rubydoc.info/gems/rake - is there somewhere else I should be looking? Happy to close this issue if I can point people to the appropriate docs.

**Comment by jimweirich** [comment]
clear, clear_actions and clear_prerequisites are all listed on http://rubydoc.info/gems/rake/0.9.2/Rake/Task
