### ISSUE TITLE
'copy' attribute ends broken

### ISSUE THREAD

**Issue by robotarmy** [jimweirich/rake#5]
Hi - i a have an attributes in a rails project named 'copy'

since i started to use bundler i am getting issues with rake conflating this with
my code - since bundler both specifies dependencies and loads dependencies
i am now having this issue.

can we not add methods to a general namepsace in rake?

1194 #############################################################################
1195 # Include the FileUtils file manipulation functions in the top level module,
1196 # but mark them private so that they don't unintentionally define methods on
1197 # other objects.
1198 
1199 include RakeFileUtils  
1200 private(_FileUtils.instance_methods(false))
1201 private(_RakeFileUtils.instance_methods(false))
1202

**Comment by jimweirich** [comment]
We have a long outstanding ticket for this (http://www.pivotaltracker.com/story/show/1223157).  Unfortunately this can't be corrected without introducing some potential incompatibilities with the existing rake files.  We are working out a way to introduce rake methods in a namespace with minimal disruption of existing rake files.

As a workaround, since the rake methods are in Object, you should only have issues if your classes are using method_missing to implement functionality.  Can you define explicit methods for the handful of conflicting methods?

**Comment by jimweirich** [comment]
Rake 0.9.x removes these from the global namespace, but then redefines the global ones with deprecation warnings.  A future version of Rake will remove the global definitions (which will be an incompatible change)

**Comment by robotarmy** [comment]
nice! thank you Jim Weirich.
